name: Build and Commit Slurm DEB Packages

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-debs:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for commits

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts equivs build-essential fakeroot debhelper curl

      - name: Build Slurm DEB Packages
        run: |
          mkdir -p /usr/src && cd /usr/src
          curl -LO https://github.com/SchedMD/slurm/archive/refs/tags/slurm-${{ vars.SLURM_VERSION }}.tar.gz
          tar -xzf slurm-${{ vars.SLURM_VERSION }}.tar.gz && cd slurm-slurm-${{ vars.SLURM_VERSION }}
          
          # Install Slurm build dependencies
          mk-build-deps -ir --tool='apt-get -qq -y -o Debug::pkgProblemResolver=yes --no-install-recommends' debian/control
          
          # Build the DEB packages
          debuild -b -uc -us >/dev/null
          
          # Move built .deb files to /debs
          mkdir -p $GITHUB_WORKSPACE/debs
          find /usr/src/ -maxdepth 1 -type f -name "*.deb" -exec mv {} $GITHUB_WORKSPACE/debs/ \;

      - name: Commit and Push .deb Packages
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add debs/
          git commit -m "Add built Slurm .deb packages for Ubuntu 24.04"
          git push origin main # Change to your branch if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
